.TH LSG 7 lsg
.SH NAME
lsg \- linux study group
.SH SYNOPSIS
.B WHERE:
LRC/LSC (Sala 6)
.P
.B WHEN:
A partir de 14/06, toda terça 17h
.P
.B WHY:
Estudar tópicos relacionados ao Linux

.SH DESCRIPTION 
Com o objetivo de aumentar o entusiasmo sobre o sistema operacional Linux em nosso curso, nós resolvemos criar o `ls -g`, o Linux Study Group.
.P
Teremos encontros semanais, que acontecerão toda terça feira 17h, a partir de 14 de Junho, no laboratório LRC/LSC (Sala 6).
.P
Em cada encontro serão abordados aspectos do linux como compiladores, ferramentas de build, bootloaders, init systems, shell scripting, interfaces gráficas, e muito mais.
.P
Além disso, no decorrer desses encontros faremos nossa própria distribuição linux do zero, desde o código fonte até a interface gráfica para que possamos aplicar todos esses conceitos vistos.
.P
Para que voce possa participar do `ls -g`, é recomendado um computador com uma distribuição linux.
.P
Participem, será uma experiência única!
.SH USAGE
Venha ao laborátio LRC/LSC (Sala 6)
.SH AUTHORS
Written by Daniel Boll, Lucas Mülling, and Pablo Hugen.
.SH SEE ALSO
.BR @pablo.hugen
.P
.BR @lucas.mulling
.P
.BR @damnboy_bot
